### ISSUE TITLE
Interface should be implementation-agnostic

### ISSUE THREAD

**Issue by marcojrfurtado** [oceanprotocol/osmosis-driver-interface#28]
If we take a look at `osmosis.py`, we have:

```
    def parse_url(url):
        """
        Parse the url to decide which driver should be loaded.
        :param url: str
        :return: Module name, str
        """
        if 'core.windows.net' in url:
            logger.info(f'Loading azure driver, url={url}.')
            return 'azure'
        elif 's3://' in url:
            logger.info(f'Loading aws driver, url={url}.')
            return 'aws'
        elif 'ipfs://' in url:
            logger.info(f'Loading IPFS driver, url={url}')
            return 'ipfs'
        else:
            logger.info(f'Loading on_premise driver, url={url}.')
            return 'on_premise'
```

I am not sure how someone can extend this, and implement their own driver, without having to modify the interface itself.

**Comment by marcojrfurtado** [comment]
Any thoughts on this? I am not sure if there is something on the roadmap regarding this.
I can definitely help with a PR on this, but I think it required some design before.

**Comment by ssallam** [comment]
@marcojrfurtado pr #29 should address this issue, but even without that change you could still introduce a new osmosis driver by delcaring the module path in the config file option `module.path`
